// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurrentWeather = { time: bigint, temperature_2m: number, wind_speed_10m: number, weather_code: number, };
