// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurrentWeather = { time: string, temperature_2m: number, wind_speed_10m: number, weather_code: number, relative_humidity_2m: number, apparent_temperature: number, precipitation_probability: number, };
