// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentWeather } from "./CurrentWeather";
import type { LocationResponse } from "./LocationResponse";

export type Weather = { current: CurrentWeather, location: LocationResponse, };
