# fly.toml app configuration file generated for web-next-dawn-brook-8580 on 2024-12-19T16:21:57-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-next-dawn-brook-8580'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
